/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_oauth.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

res_auth *
request_authorization_1(req_auth *argp, CLIENT *clnt)
{
	static res_auth clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_authorization,
		(xdrproc_t) xdr_req_auth, (caddr_t) argp,
		(xdrproc_t) xdr_res_auth, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

res_acc_token *
request_access_token_1(req_acc_token *argp, CLIENT *clnt)
{
	static res_acc_token clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, request_access_token,
		(xdrproc_t) xdr_req_acc_token, (caddr_t) argp,
		(xdrproc_t) xdr_res_acc_token, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

res_val_del_act *
validate_delegated_action_1(req_val_del_act *argp, CLIENT *clnt)
{
	static res_val_del_act clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, validate_delegated_action,
		(xdrproc_t) xdr_req_val_del_act, (caddr_t) argp,
		(xdrproc_t) xdr_res_val_del_act, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

res_approve_req_token *
approve_request_token_1(req_approve_req_token *argp, CLIENT *clnt)
{
	static res_approve_req_token clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, approve_request_token,
		(xdrproc_t) xdr_req_approve_req_token, (caddr_t) argp,
		(xdrproc_t) xdr_res_approve_req_token, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
